name: Feature Request
description: File a feature request
title: "[FEATURE] <title>"
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: checkboxes
    attributes:
      label: Is there an existing request for this?
      description: Please search to see if an request already exists for the feature you want.
      options:
      - label: I have searched the existing requests
        required: true
  - type: textarea
    attributes:
      label: Feature Description
      description: A description of feature you would like to see in the plugin.
    validations:
      required: true
